#!/bin/bash
# Configure grok using deployment profiles and persistent user state.
set -euo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/org-runtime.sh"

TARGET=grok
SCRIPT_DIR=$(dirname "$0")

# --- Persistent data volume ---
# A single Docker volume at ~/.data/ stores all agent data and shell history
# to survive container rebuilds. The volume mounts root-owned on first create; the
# chown is idempotent and every feature that touches ~/.data does it, since any of
# them may run first.
org_prepare_data
mkdir -p "$DATA/$TARGET"

# --- Symlink agent data directories into the persistent volume ---
# Persist state, then point the legacy executable location at the image version.
vol_dir="$DATA/$TARGET"
home_dir="$HOME/.$TARGET"
if [ -d "$home_dir" ] && [ ! -L "$home_dir" ]; then
    if [ -z "$(ls -A "$vol_dir" 2>/dev/null)" ]; then
        cp -a "$home_dir/." "$vol_dir/"
    fi
    rm -rf "$home_dir"
fi
ln -sfn "$vol_dir" "$home_dir"
mkdir -p "$home_dir/bin"
ln -sfn /usr/local/lib/org-features/grok/grok "$home_dir/bin/grok"

# --- Grok config from the configured profiles ---
# Grok reads /etc/grok/managed_config.toml as fleet defaults that the user's own
# ~/.grok/config.toml overrides — the analogue of Codex's /etc/codex/config.toml, kept
# system-level for the same reason: ~/.grok/config.toml is user-owned (the installer
# records its update channel there, /settings writes there) and sits on the persisted
# volume, so generated content there would go stale and shadow later profile changes.
#
# Each profile's grok.toml fragment holds ONLY [auth_provider.<name>] and
# [model."<profile>/<name>"] tables, so fragments concatenate into valid TOML; the single
# [models] table is emitted here — `default` is the first model key, `allowed_models` is
# every key. The allowlist hides Grok's built-in xAI-hosted grok-4.x entries, which need a
# `grok login`/XAI_API_KEY and would send code to x.ai — the same reason every OpenCode
# profile disables its bundled Zen provider. Telemetry is off for the same data-boundary
# reason. A user can lift either in ~/.grok/config.toml (user layer wins).
GROK_MANAGED_CONFIG="/etc/grok/managed_config.toml"

# Keep this array outside the profile guard so an empty selection removes generated config.
GROK_FILES=()
if [ -n "$CONFIGURED_PROFILES" ]; then
    PROFILES_LINE="CONFIGURED_PROFILES=$CONFIGURED_PROFILES"
    if [ -n "$PROFILES_LINE" ]; then
        CSV="${PROFILES_LINE#CONFIGURED_PROFILES=}"
        CSV="${CSV//$'\r'/}"
        IFS=',' read -ra CONFIGURED <<< "$CSV"

        for profile in "${CONFIGURED[@]}"; do
            if [ -f "$PROFILES_DIR/$profile/grok.toml" ]; then
                GROK_FILES+=("$profile")
            fi
        done
    fi
fi

if [ ${#GROK_FILES[@]} -ge 1 ]; then
    GROK_PATHS=()
    for p in "${GROK_FILES[@]}"; do GROK_PATHS+=("$PROFILES_DIR/$p/grok.toml"); done
    # Model keys in declaration order: [model."aws/grok-4.6"] -> aws/grok-4.6
    mapfile -t GROK_KEYS < <(sed -n 's/^\[model\."\([^"]*\)"\]$/\1/p' "${GROK_PATHS[@]}")
    sudo mkdir -p "$(dirname "$GROK_MANAGED_CONFIG")"
    {
        echo "# Generated by the grok dev container feature from configured profiles."
        echo "# User-specific Grok settings belong in ~/.grok/config.toml, which overrides this file."
        if [ ${#GROK_KEYS[@]} -ge 1 ]; then
            GROK_ALLOWED=$(printf '"%s", ' "${GROK_KEYS[@]}")
            echo ""
            echo "[models]"
            echo "default = \"${GROK_KEYS[0]}\""
            echo "allowed_models = [${GROK_ALLOWED%, }]"
        fi
        echo ""
        echo "[features]"
        echo "telemetry = false"
        for f in "${GROK_PATHS[@]}"; do echo ""; cat "$f"; done
    } | sudo tee "$GROK_MANAGED_CONFIG" >/dev/null
# Remove OUR generated file when no configured profile provides one (a profile switch),
# but never a hand-written one.
elif [ -f "$GROK_MANAGED_CONFIG" ] && grep -q '^# Generated by the grok dev container feature' "$GROK_MANAGED_CONFIG"; then
    sudo rm -f "$GROK_MANAGED_CONFIG"
fi

