#!/bin/bash
set -euo pipefail
FEATURE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
. "$FEATURE_DIR/org-build.sh"
org_feature_init "$FEATURE_DIR" shell-history

INCLUDE="${INCLUDE:-bash,zsh,python,node}"
DIRECTORY="${DIRECTORY:-.data/shell-history}"
[[ "$INCLUDE" =~ ^((bash|zsh|python|node|psql|sqlite3|less),?)+$ ]] \
    || { echo "shell-history: include takes bash, zsh, python, node, psql, sqlite3, less." >&2; exit 1; }
[[ "$DIRECTORY" =~ ^[A-Za-z0-9._/-]+$ ]] \
    || { echo "shell-history: invalid directory '$DIRECTORY'." >&2; exit 1; }
case "$DIRECTORY" in
    /*) DIR_EXPR="$DIRECTORY" ;;
    *)  DIR_EXPR="\$HOME/$DIRECTORY" ;;
esac
has() { case ",$INCLUDE," in *",$1,"*) return 0 ;; *) return 1 ;; esac; }

DEST=/usr/local/share/org-features/shell-history
printf 'INCLUDE=%s\nDIRECTORY=%s\n' "$INCLUDE" "$DIRECTORY" > "$DEST/options.env"

# Sourced by bash and zsh at interactive startup, before the user's rc files.
{
    echo '# Generated by the shell-history feature; sourced from /etc/bash.bashrc and /etc/zsh/zshrc.'
    echo "__shell_history_dir=\"$DIR_EXPR\""
    # Only once the create step has made it: a shell opened earlier, or one whose
    # HOME has no volume (sudo -i), keeps its default history.
    echo 'if [ -d "$__shell_history_dir" ] && [ -w "$__shell_history_dir" ]; then'
    if has zsh; then cat <<'SH'
    if [ -n "${ZSH_VERSION:-}" ]; then
        HISTFILE="$__shell_history_dir/.zsh_history"
        # Write per command: a rebuild SIGKILLs open terminals before they save on exit.
        setopt INC_APPEND_HISTORY
    fi
SH
    fi
    if has bash; then cat <<'SH'
    if [ -n "${BASH_VERSION:-}" ]; then
        HISTFILE="$__shell_history_dir/.bash_history"
        shopt -s histappend
        case "${PROMPT_COMMAND:-}" in
            *"history -a"*) ;;
            *) PROMPT_COMMAND="history -a${PROMPT_COMMAND:+; $PROMPT_COMMAND}" ;;
        esac
    fi
SH
    fi
    has python  && echo '    export PYTHON_HISTORY="$__shell_history_dir/python_history"'
    has node    && echo '    export NODE_REPL_HISTORY="$__shell_history_dir/node_repl_history"'
    has psql    && echo '    export PSQL_HISTORY="$__shell_history_dir/psql_history"'
    has sqlite3 && echo '    export SQLITE_HISTORY="$__shell_history_dir/sqlite_history"'
    has less    && echo '    export LESSHISTFILE="$__shell_history_dir/lesshst"'
    echo 'fi'
    echo 'unset __shell_history_dir'
} > "$DEST/history.sh"
chmod 644 "$DEST/history.sh"

# One marked line per rc; idempotent across rebuilt layers. ~/.zshrc too: VS Code's
# zsh integration resets HISTFILE after /etc/zsh/zshrc and before ~/.zshrc, and zsh
# reads history only after the last rc. The system file still covers a dotfiles
# repo that replaces ~/.zshrc, outside VS Code.
LINE="[ -r $DEST/history.sh ] && . $DEST/history.sh  # shell-history feature"
USER_ZSHRC="$(getent passwd "$_REMOTE_USER" | cut -d: -f6)/.zshrc"
for rc in /etc/bash.bashrc /etc/zsh/zshrc "$USER_ZSHRC"; do
    [ -f "$rc" ] || continue
    grep -qF '# shell-history feature' "$rc" || printf '\n%s\n' "$LINE" >> "$rc"
done
