#!/bin/bash
# The feature needs Node, which the autogenerated test cannot add; scenarios.json provides it.
set -euo pipefail
FEATURE=/usr/local/share/org-features/playwright
expected=$(jq -r '.options.version.default' "$FEATURE/devcontainer-feature.json")
playwright-cli --version | grep -F "$expected"
# The build installed Chromium's OS packages and certutil.
bash "$FEATURE/bundled-playwright.sh" install-deps --dry-run chromium | grep -F "All system dependencies are installed"
command -v certutil
# The create hook moved the cache onto the volume and downloaded Chromium into it.
[ "$(readlink "$HOME/.cache/ms-playwright")" = "$HOME/.data/playwright" ]
ls "$HOME/.data/playwright" | grep -q '^chromium-'
# The start hook imported the local CAs Chromium needs, if the base has any.
if find /usr/local/share/ca-certificates -name '*.crt' | grep -q .; then
    certutil -L -d "sql:$HOME/.pki/nssdb" | grep -q 'C,,'
fi
# Chromium is the CLI's default browser and launches headless with no --browser flag.
jq -e '.browser.browserName == "chromium"' "$HOME/.playwright/cli.config.json"
playwright-cli open 'data:text/html,<title>feature-ok</title>'
playwright-cli eval 'document.title' | grep -F feature-ok
playwright-cli close
echo "Feature smoke test passed."
