#!/bin/bash
# Configure codex using deployment profiles and persistent user state.
set -euo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/org-runtime.sh"

TARGET=codex
SCRIPT_DIR=$(dirname "$0")

# --- Persistent data volume ---
# A single Docker volume at ~/.data/ stores all agent data and shell history
# to survive container rebuilds. The volume mounts root-owned on first create; the
# chown is idempotent and every feature that touches ~/.data does it, since any of
# them may run first.
org_prepare_data
mkdir -p "$DATA/$TARGET"

# --- Symlink agent data directories into the persistent volume ---
# If the volume directory is empty and the home directory has content from the feature
# installer, seed the volume with those files before symlinking.
vol_dir="$DATA/$TARGET"
home_dir="$HOME/.$TARGET"
if [ -d "$home_dir" ] && [ ! -L "$home_dir" ]; then
    if [ -z "$(ls -A "$vol_dir" 2>/dev/null)" ]; then
        cp -a "$home_dir/." "$vol_dir/"
    fi
    rm -rf "$home_dir"
fi
ln -sfn "$vol_dir" "$home_dir"

# --- Codex CLI config from the configured profiles ---
# Codex writes user choices (project trust, features, UI settings, plugin state) to
# ~/.codex/config.toml, so that file is left strictly user-owned — nothing here ever
# writes it. Generated provider defaults go to /etc/codex/config.toml, the
# lowest-precedence Codex layer, so a developer's own settings always win and the
# generated half can be replaced wholesale on every create.
#
# A profile opts in to Codex by shipping a config.toml; profiles without one get no
# Codex config. That per-profile opt-in is the whole point of generating this file
# rather than shipping a static one with the feature: a container whose profile has no
# Codex config must end up with NO config, not somebody else's.
#
# No merging: use the first configured profile that provides a config.toml.
CODEX_SYSTEM_CONFIG="/etc/codex/config.toml"

# Keep this array outside the profile guard so an empty selection removes generated config.
CODEX_FILES=()
if [ -n "$CONFIGURED_PROFILES" ]; then
    PROFILES_LINE="CONFIGURED_PROFILES=$CONFIGURED_PROFILES"
    if [ -n "$PROFILES_LINE" ]; then
        CSV="${PROFILES_LINE#CONFIGURED_PROFILES=}"
        CSV="${CSV//$'\r'/}"
        IFS=',' read -ra CONFIGURED <<< "$CSV"

        for profile in "${CONFIGURED[@]}"; do
            if [ -f "$PROFILES_DIR/$profile/config.toml" ]; then
                CODEX_FILES+=("$profile")
            fi
        done
    fi
fi

if [ ${#CODEX_FILES[@]} -ge 1 ]; then
    sudo mkdir -p "$(dirname "$CODEX_SYSTEM_CONFIG")"
    {
        echo "# Generated by the codex dev container feature from configured profiles."
        echo "# User-specific Codex settings belong in ~/.codex/config.toml."
        echo ""
        cat "$PROFILES_DIR/${CODEX_FILES[0]}/config.toml"
    } | sudo tee "$CODEX_SYSTEM_CONFIG" >/dev/null
# Remove OUR generated file when no configured profile provides one (a profile switch),
# but never a hand-written one.
elif [ -f "$CODEX_SYSTEM_CONFIG" ] && grep -q '^# Generated by the codex dev container feature' "$CODEX_SYSTEM_CONFIG"; then
    sudo rm -f "$CODEX_SYSTEM_CONFIG"
fi

# --- Codex model picker: drop the duplicate `global.` ids ---
# Bedrock Runtime lists every OpenAI model twice, once per cross-region inference
# profile (global.openai.* and us.openai.*), so the /model picker shows eight entries
# for four models. model_catalog_json replaces Codex's built-in catalog with a file,
# letting us keep only the `us.` half.
#
# It must be GENERATED, not tracked: a catalog entry REPLACES the built-in one and Codex
# rejects a partial entry (`missing field display_name`), so the file has to carry every
# field — including the per-model instruction templates, which change on each Codex
# release. Regenerating from the installed binary from this feature release keeps it in step.
#
# A model_catalog_json path that does not exist is a FATAL config error ("Error: No such
# file or directory") that bricks every codex invocation, so the profile config.toml
# deliberately does not name it: the key is appended here only after the file is
# successfully written. Warn-only on failure — this script runs under `set -euo pipefail`
# and a stale or missing catalog must never cost the create.
#
# Resolve the binary by path as well as PATH: a feature postCreateCommand is not
# guaranteed a login shell, so ~/.local/bin (where the installer puts codex) may be
# absent from PATH even though the build installed it.
CODEX_BIN="$(command -v codex 2>/dev/null || true)"
if [ -z "$CODEX_BIN" ] && [ -x "$HOME/.local/bin/codex" ]; then
    CODEX_BIN="$HOME/.local/bin/codex"
fi

CODEX_CATALOG="/etc/codex/model-catalog.json"
if [ ${#CODEX_FILES[@]} -ge 1 ] && [ -n "$CODEX_BIN" ]; then
    CODEX_CATALOG_TMP="$(mktemp)"
    if timeout 60 "$CODEX_BIN" debug models 2>/dev/null \
        | jq '.models |= map(select(.slug | startswith("global.") | not))' \
        > "$CODEX_CATALOG_TMP" 2>/dev/null \
        && [ -s "$CODEX_CATALOG_TMP" ] \
        && [ "$(jq '.models | length' "$CODEX_CATALOG_TMP" 2>/dev/null || echo 0)" -gt 0 ]; then
        sudo install -m 644 "$CODEX_CATALOG_TMP" "$CODEX_CATALOG"
        echo "model_catalog_json = \"$CODEX_CATALOG\"" \
            | sudo tee -a "$CODEX_SYSTEM_CONFIG" >/dev/null
    else
        # Leave the key out entirely rather than point at a missing file.
        echo -e "\e[33m⚠️  Could not generate the Codex model catalog; the /model picker will\e[0m"
        echo -e "\e[33m   list the duplicate global.* ids. Codex itself is unaffected.\e[0m"
        sudo rm -f "$CODEX_CATALOG"
    fi
    rm -f "$CODEX_CATALOG_TMP"
elif [ -f "$CODEX_CATALOG" ]; then
    # No Codex profile config any more — drop the file we generated.
    sudo rm -f "$CODEX_CATALOG"
fi

# --- Warn when the user layer shadows the profile ---
# The USER layer wins over the system layer, so a model/model_provider set in
# ~/.codex/config.toml silently shadows every profile change. Warn only — the file is
# the user's; never edit it from here.
CODEX_USER_CONFIG="$HOME/.codex/config.toml"
CODEX_SHADOW_RE='^[[:space:]]*(model|model_provider)[[:space:]]*=|^[[:space:]]*\[model_providers\.'
if [ ${#CODEX_FILES[@]} -ge 1 ] && [ -f "$CODEX_USER_CONFIG" ] \
    && grep -qE "$CODEX_SHADOW_RE" "$CODEX_USER_CONFIG"; then
    echo ""
    echo -e "\e[33m⚠️  ~/.codex/config.toml sets its own model/provider, which overrides the\e[0m"
    echo -e "\e[33m   profile config in $CODEX_SYSTEM_CONFIG:\e[0m"
    grep -nE "$CODEX_SHADOW_RE" "$CODEX_USER_CONFIG" | sed 's/^/     /' || true
    echo "   Remove those lines from ~/.codex/config.toml to follow the profile."
    echo ""
fi
